In [3]:
import numpy as np
import pandas as pd

### DataFrames

In [4]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [5]:
df = pd.DataFrame(data, columns=columns)

In [6]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [7]:
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [8]:
df.head(n=3)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

### Series

In [9]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [10]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [13]:
df[['Engine HP']]

   Engine HP
0      138.0
1        NaN
2      218.0
3      194.0
4      261.0

In [14]:
df[['Make', 'Model', 'Engine HP', 'MSRP']]

      Make     Model  Engine HP   MSRP
0   Nissan    Stanza      138.0   2000
1  Hyundai    Sonata        NaN  27150
2    Lotus     Elise      218.0  54990
3      GMC    Acadia      194.0  34450
4   Nissan  Frontier      261.0  32340

In [17]:
df['id'] = np.arange(1, len(df) + 1)

In [18]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

### Index

In [19]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [20]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [22]:
df.loc[[1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2

In [23]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: 1, dtype: object

In [24]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [25]:
df.loc[['a', 'b']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2

In [26]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: b, dtype: object

In [27]:
df.iloc[[0, 1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2

In [28]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [30]:
df.reset_index(drop=True, inplace=True)

In [31]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

### Element-wise operations

In [32]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [33]:
df['Engine HP'] * 100

0    13800.0
1        NaN
2    21800.0
3    19400.0
4    26100.0
Name: Engine HP, dtype: float64

In [36]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [40]:
df[df['Year'] >= 2015]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [41]:
df[(df['Year'] >= 2015) & (df['Engine HP'] > 200)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

### String operations

In [42]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [44]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [45]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [46]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [49]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [50]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340,5

### Summarizing operations

In [52]:
df['MSRP'].max()

np.int64(54990)

In [53]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [55]:
df.describe().round()

         Year  Engine HP  Engine Cylinders     MSRP   id
count     5.0        4.0               5.0      5.0  5.0
mean   2010.0      203.0               4.0  30186.0  3.0
std      11.0       51.0               1.0  18985.0  2.0
min    1991.0      138.0               4.0   2000.0  1.0
25%    2010.0      180.0               4.0  27150.0  2.0
50%    2017.0      206.0               4.0  32340.0  3.0
75%    2017.0      229.0               4.0  34450.0  4.0
max    2017.0      261.0               6.0  54990.0  5.0

In [57]:
df.Make.nunique()

4

In [58]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
id                   5
dtype: int64

### Missing values

In [62]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

### Grouping

In [63]:
df.groupby('Transmission Type')['MSRP'].min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

In [64]:
df.groupby('Transmission Type')['MSRP'].mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [71]:
df.groupby(['Transmission Type', 'Vehicle_Style'])[['MSRP', 'Engine HP']].mean()

                                    MSRP  Engine HP
Transmission Type Vehicle_Style
AUTOMATIC         4dr_suv        34450.0      194.0
                  sedan          27150.0        NaN
MANUAL            convertible    54990.0      218.0
                  pickup         32340.0      261.0
                  sedan           2000.0      138.0

Getting the NumPy arrays

In [72]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [73]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000,
  'id': 1},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150,
  'id': 2},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990,
  'id': 3},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450,
  'id': 4},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340,
  'id': 5}]